components: Ensure deleting a blueprint also deletes any associated images
osbuild/cockpit-composer pull request #1767
Opened 2023-02-02 14:06 UTC by regexowl

Fixes #1694.

This adds a deletion of any associated images when a blueprint is deleted.

Copy for the modal was also updated to inform the user that the images will be deleted together with the blueprint.

2023-02-09 20:31 UTC, jkozol requested changes
This works as expected :)

But can you create a filtered thunk for deletion in the images. That way we can dispatch an action to delete filtered images more generally. This also would mean the `deleteDlueprint` thunk will only have to dispatch a single action instead of loop dispatching actions.

2023-02-10 10:28 UTC, regexowl commented
@jkozol Updated. Please let me know if it's similar to what you had in mind.

2024-01-15 08:27 UTC, regexowl commented
@jkozol This PR might also be a bit stale. Should I close it?

2024-01-16 08:25 UTC, regexowl commented
Closing this PR as stale

2024-01-16 08:25 UTC, closed without merging