Align testing with cockpit-project
osbuild/cockpit-composer pull request #2044
Opened 2024-08-20 15:34 UTC by croissanne

Cockpit defines their gating tests upstream, in `test/browser`.

2024-08-21 08:55 UTC, kingsleyzissou approved these changes
Looks good to me, from what I can tell. Do we want to try ask for one of the cockpit team to give a review too?

2024-08-21 09:27 UTC, martinpitt requested changes
Thanks @croissanne this makes sense! However, to really validate this I recommend to actually enable at least one OS in your [packit config](https://github.com/osbuild/cockpit-composer/blob/main/packit.yaml), so that they run in upstream PRs. After all, you want to shift left the gating tests, no? Otherwise this will just bitrot.

2024-08-21 09:27 UTC, martinpitt commented on test/browser/browser.sh
> +dnf update -y pam || true
That was fixed over a year ago, you probably don't need this.

2024-08-21 09:27 UTC, martinpitt commented
Note that COPR has some serious problems today, builds take ages.. so the TF results will also take a while, but they do come in eventually.

2024-08-21 09:37 UTC, croissanne commented
Is it just
```
  - job: tests
    identifier: self
    trigger: pull_request
    targets:
      -...

```?

2024-08-21 09:43 UTC, martinpitt commented
@croissanne I saw some "is it just.." question fly by, apparently you removed the comment. But the extra commit looks good in general. You mostly need to keep the `targets:` list up to date and to what you support in main. So let's wait for the results! :coffee:

2024-08-21 09:43 UTC, martinpitt submitted a review, later dismissed
Looks good in general, bots have the last word.

2024-08-21 11:29 UTC, martinpitt commented
@croissanne FTR, your [downstream dist-git](https://src.fedoraproject.org/rpms/cockpit-composer/tree/rawhide) still needs two things: The [.fmf/version stamp](https://src.fedoraproject.org/rpms/cockpit-podman/blob/rawhide/f/.fmf/version) and a [plan](https://src.fedoraproject.org/rpms/cockpit-podman/blob/rawhide/f/plans/upstream.fmf) that runs the tests from the dist-git's source tarball.

2024-08-21 11:46 UTC, croissanne commented
> @croissanne FTR, your [downstream dist-git](https://src.fedoraproject.org/rpms/cockpit-composer/tree/rawhide) still needs two things: The [.fmf/version stamp](https://src.fedoraproject.org/rpms/cockpit-podman/blob/rawhide/f/.fmf/version) and a [plan](https://src.fedoraproject.org/rpms/cockpit-podman/blob/rawhide/f/plans/upstream.fmf) that runs the tests from the dist-git's source tarball.

will add those as soon as the tests succeed here

2024-08-21 14:36 UTC, croissanne commented
/packit test

2024-08-21 18:05 UTC, kingsleyzissou commented
Weird, looks like some of those rpm builds completed successfully. But the jobs are still pending

2024-08-21 18:17 UTC, croissanne commented
> Weird, looks like some of those rpm builds completed successfully. But the jobs are still pending

naw it's the srpm jobs that are completed. Copr is rlly struggling still 
![afbeelding](https://github.com/user-attachments/assets/a653672e-25fb-40e0-a00e-6db0d000e315)

https://copr.fedorainfracloud.org/status/stats/

2024-08-22 11:35 UTC, kingsleyzissou approved these changes
🎉 🎉

2024-08-22 11:42 UTC, merged